#!/usr/bin/env ruby

require 'fileutils'
include FileUtils

def record_begins
  now = Time.now.to_i
  (now - (3600*3)).step(now, 300).map { |t| Time.at(t - t % 300).utc }
end

mkdir_p records_dir="tmp/records"
one_minute_file="./spec/fixtures/five-minutes.ogg"

record_begins.each_with_index do |record_begin, index|
  record_format = index > 24 ? "wav" : "ogg"
  record_file = "#{records_dir}/#{record_begin.strftime("%Y/%m-%b/%d-%a/%Hh%M")}.#{record_format}"
  unless File.exists?(record_file)
    puts "create #{record_file}"
    FileUtils.mkdir_p File.dirname(record_file)
    command = record_format == "ogg" ? "cp" : "sox"
    system "#{command} #{one_minute_file} #{record_file}"
  end
end

