#!/usr/bin/env ruby

ENV["RAILS_ENV"] ||= (ARGV.first  or "production")
require File.expand_path('../../config/environment', __FILE__)

Thread.new do
  Delayed::Worker.new.start
end

UDP::Receiver.init
Upload.daemon
